<a href="https://colab.research.google.com/github/noahlim99/DL/blob/main/%08Pytorch_Simple_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.__version__

'2.4.1+cu121'

In [ ]:
torch.manual_seed(316)

In [ ]:
features = torch.randn((1, 5))
features

tensor([[ 1.5730,  0.0812, -2.2865, -2.2991, -2.6735]])

In [ ]:
features.shape

torch.Size([1, 5])

In [ ]:
weights = torch.randn((1,5))
bias = torch.randn((1,1))

In [ ]:
z = torch.sum(features * weights) + bias

In [ ]:
z

tensor([[-4.9458]])

In [ ]:
z = torch.mm(features, weights.view(-1,1)) + bias

In [ ]:
z

tensor([[-4.9458]])

In [ ]:
print(weights.view(-1,1))

tensor([[-0.4179],
        [-0.3285],
        [-1.3326],
        [ 1.5805],
        [ 1.5407]])


In [ ]:
def sigmoid(x) :
  return 1 / (1 + torch.exp(-x))

In [ ]:
a = sigmoid(z)

In [ ]:
a

tensor([[0.0071]])

In [ ]:
a.item()

0.007062825374305248

*With a Hidden Layer*

In [ ]:
torch.manual_seed(318)

In [ ]:
n_input = 3
n_hidden = 2
n_output = 1

In [ ]:
features = torch.randn((1, n_input))

In [ ]:
print(features)

tensor([[-1.1069, -1.0308,  1.6005]])


In [ ]:
features.shape

torch.Size([1, 3])

In [ ]:
W1 = torch.randn(n_input, n_hidden)

In [ ]:
print(W1)

tensor([[-1.4133, -1.5084],
        [-1.8982, -0.3882],
        [-0.5675, -1.1959]])


In [ ]:
W2 = torch.randn(n_hidden, n_output)

In [ ]:
print(W2)

tensor([[-0.8328],
        [-0.5913]])


In [ ]:
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [ ]:
print(B1)

tensor([[ 0.2756, -0.8890]])


In [ ]:
Z1 = torch.mm(features, W1) + B1

In [ ]:
Z1

tensor([[ 2.8885, -0.7332]])

In [ ]:
Z1.shape

torch.Size([1, 2])

In [ ]:
A1 = sigmoid(Z1)

In [ ]:
A1

tensor([[0.9473, 0.3245]])

In [ ]:
A1.shape

torch.Size([1, 2])

In [ ]:
Z2 = torch.mm(A1, W2) + B2

In [ ]:
Z2

tensor([[-0.0503]])

In [ ]:
A2 = sigmoid(Z2)

In [ ]:
A2

tensor([[0.4874]])

In [ ]:
y_hat = A2.item()

In [ ]:
print(y_hat)

0.4874347746372223


In [ ]:
import torch
from torch import nn
from collections import OrderedDict

model = nn.Sequential(
        nn.Linear(784, 256),
        nn.Sigmoid(),
        nn.Linear(256, 10),
        nn.Softmax(dim=1)
)

W1_shape = model[0].weight.shape
print(f"W[1] = ({W1_shape[1]}, {W1_shape[0]})")

W[1] = (784, 256)


In [ ]:
model[0].weight.shape

torch.Size([256, 784])

In [ ]:
model[2].weight.shape

torch.Size([10, 256])

In [ ]:
model[2].weight.numel() + model[2].bias.numel()

2570

In [ ]:
model[0].weight.numel() + model[0].bias.numel()

200960

In [ ]:
num_parameter_layer1 = model[0].weight.numel() + model[0].bias.numel()
num_parameter_layer2 = model[2].weight.numel() + model[2].bias.numel()
num_parameter = num_parameter_layer1 + num_parameter_layer2
print(f"Total number of parameters:", num_parameter)

Total number of parameters: 203530


In [ ]:
total_params = sum(p.numel() for p in model.parameters())
print(f"Total number of parameters: {total_params}")

Total number of parameters: 203530
